
// //@ts-nocheck
// "use client";

// import { format } from "date-fns";
// import jsPDF from "jspdf";
// import autoTable from "jspdf-autotable";
// import { Download, FileSpreadsheet } from "lucide-react";
// import dynamic from "next/dynamic";
// import { useState } from "react";
// import * as XLSX from "xlsx";
// import RevenueDescriptionTooltip from "./RevenueDescriptionTooltip";

// const ReactApexChart = dynamic(() => import("react-apexcharts"), { ssr: false });

// const areaChartOptions = {
//     chart: { height: 350, type: "area" },
//     dataLabels: { enabled: false },
//     stroke: { curve: "smooth", width: 2 },
//     legend: { position: "right", verticalAlign: "center" },
//     xaxis: { categories: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] },
//     yaxis: { title: { text: "Revenue" } },
//     tooltip: { y: { formatter: (val: number) => `$${val}` } },
// };

// type RangeOption = "Monthly" | "Quarterly" | "Half-Yearly" | "Yearly" | "All";

// const AreaChart = ({
//     title,
//     data,
// }: {
//     title: string;
//     data: { revenue: { year: string; months: number[] }[]; description?: string };
// }) => {
//     const [selectedRange, setSelectedRange] = useState<RangeOption>("All");
//     const monthsLabels = areaChartOptions.xaxis.categories;

//     // ------------------- Filtered Series -----------------
//     const filteredSeries = data?.revenue?.map(item => {
//         let months = item.months;
//         switch (selectedRange) {
//             case "Monthly": months = months.slice(-1); break;
//             case "Quarterly": months = months.slice(-3); break;
//             case "Half-Yearly": months = months.slice(-6); break;
//             case "Yearly":
//             case "All":
//             default: months = months;
//         }
//         return { name: item.year, data: months };
//     });

//     // Filtered month labels
//     const filteredMonths = (() => {
//         const len = filteredSeries?.[0]?.data?.length || 0;
//         return monthsLabels.slice(monthsLabels.length - len);
//     })();

//     const getHighlightCount = () => {
//         switch (selectedRange) {
//             case "Monthly": return 1;
//             case "Quarterly": return 3;
//             case "Half-Yearly": return 6;
//             default: return filteredMonths.length;
//         }
//     };
//     const lastCols = getHighlightCount();

//     // ------------------- PDF Download -----------------
//     const handleDownloadPDF = async () => {
//         const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
//         const pageW = doc.internal.pageSize.getWidth();
//         const pageH = doc.internal.pageSize.getHeight();
//         const margin = { left: 12, right: 12, top: 16 };
//         let currentY = margin.top;

//         // Logo
//         const logoUrl = "/logo.png";
//         const imgProps = await new Promise<HTMLImageElement>((resolve) => {
//             const img = new Image();
//             img.src = logoUrl;
//             img.onload = () => resolve(img);
//         });
//         const logoWidth = 40;
//         const logoHeight = (imgProps.height / imgProps.width) * logoWidth;
//         doc.addImage(logoUrl, "PNG", margin.left, currentY, logoWidth, logoHeight);

//         // Header
//         const centerX = pageW / 2;
//         doc.setFontSize(14);
//         doc.setFont("helvetica", "bold");
//         doc.text("DgPrint24", centerX, currentY + logoHeight / 2 + 2, { align: "center" });
//         currentY += logoHeight + 6;
//         doc.setFontSize(14);
//         doc.text(title, centerX, currentY, { align: "center" });
//         currentY += 6;

//         doc.setFontSize(10);
//         doc.text(`Generated by Admin at ${format(new Date(), "dd/MM/yyyy hh:mm a")}`, margin.left, currentY);
//         currentY += 6;
//         // if (data.description) {
//         //     const wrappedDesc = doc.splitTextToSize(data.description, pageW - margin.left - margin.right);
//         //     const boxHeight = wrappedDesc.length * 6 + 4;
//         //     doc.setDrawColor(10, 51, 67);
//         //     doc.setFillColor(240, 240, 240);
//         //     doc.rect(margin.left, currentY, pageW - margin.left - margin.right, boxHeight, "FD");
//         //     doc.text(wrappedDesc, margin.left + 2, currentY + 6);
//         //     currentY += boxHeight + 4;
//         // }

//         // ------------------- Filter series for download -----------------
//         const filteredSeriesForDownload = filteredSeries.filter(s =>
//             s.data.some(v => v !== 0) // only include series with data
//         );

//         // Table
//         const tableBody: any[] = [];
//         let headerRow: string[] = [];

//         if (filteredSeriesForDownload.length > 1) {
//             headerRow = ["Month", ...filteredSeriesForDownload.map(s => s.name)];
//             filteredMonths.forEach((month, idx) => {
//                 const row = [month];
//                 filteredSeriesForDownload.forEach(s => row.push((s.data[idx] ?? 0).toFixed(2)));
//                 tableBody.push(row);
//             });
//         } else {
//             headerRow = ["Year", "Month", "Revenue"];
//             filteredSeriesForDownload.forEach(s => {
//                 filteredMonths.forEach((month, idx) => {
//                     tableBody.push([s.name, month, (s.data[idx] ?? 0).toFixed(2)]);
//                 });
//             });
//         }

//         autoTable(doc, {
//             startY: currentY + 2,
//             head: [headerRow],
//             body: tableBody,
//             styles: { fontSize: 10, cellPadding: 3 },
//             headStyles: { fillColor: [10, 51, 67], textColor: 255 },
//             theme: "grid",
//             didDrawPage: () => {
//                 doc.setFontSize(10);
//                 doc.setTextColor(100);
//                 doc.text("Developed by ZSI.ai", pageW / 2, pageH - 10, { align: "center" });
//             }
//         });

//         doc.save(`revenue_report_${selectedRange}_${new Date().toLocaleDateString()}.pdf`);
//     };

//     // ------------------- Excel Download -----------------
//     const handleDownloadExcel = () => {
//         const aoa: any[][] = [];
//         aoa.push(["DGPRINT24"]);
//         aoa.push([title]);
//         aoa.push([`Generated at ${format(new Date(), "dd/MM/yyyy hh:mm a")}`]);
//         aoa.push([]);
//         aoa.push(["Description"]);
//         aoa.push([data.description || "—"]);
//         aoa.push([]);

//         const filteredSeriesForDownload = filteredSeries.filter(s => s.data.some(v => v !== 0));

//         let headerRow: string[] = [];
//         if (filteredSeriesForDownload.length > 1) {
//             headerRow = ["Month", ...filteredSeriesForDownload.map(s => s.name)];
//             aoa.push(headerRow);
//             filteredMonths.forEach((month, idx) => {
//                 const row = [month];
//                 filteredSeriesForDownload.forEach(s => row.push((s.data[idx] ?? 0).toFixed(2)));
//                 aoa.push(row);
//             });
//         } else {
//             headerRow = ["Year", "Month", "Revenue"];
//             aoa.push(headerRow);
//             filteredSeriesForDownload.forEach(s => {
//                 filteredMonths.forEach((month, idx) => {
//                     aoa.push([s.name, month, (s.data[idx] ?? 0).toFixed(2)]);
//                 });
//             });
//         }

//         const ws = XLSX.utils.aoa_to_sheet(aoa);

//         const totalCols = headerRow.length;
//         for (let r = 8; r < aoa.length; r++) {
//             for (let c = totalCols - lastCols; c < totalCols; c++) {
//                 const cellRef = XLSX.utils.encode_cell({ r, c });
//                 if (!ws[cellRef]) continue;
//                 ws[cellRef].s = { fill: { fgColor: { rgb: "C8E6FF" } } };
//             }
//         }

//         const wb = XLSX.utils.book_new();
//         XLSX.utils.book_append_sheet(wb, ws, "Revenue Report");
//         XLSX.writeFile(wb, `Revenue_Report_${selectedRange}_${new Date().toLocaleDateString()}.xlsx`);
//     };

//     return (
//         <div className="p-10 bg-white shadow-2xl">
//             <div className="flex flex-col xl:flex-row md:justify-between gap-4 mb-4 items-start md:items-center">
//                 <div className="flex items-center gap-2">
//                     <h2 className="text-lg font-semibold text-black">{title}</h2>
//                     {data.description && <RevenueDescriptionTooltip description={data.description} />}
//                 </div>

//                 <div className="flex gap-2 items-center">
//                     <select
//                         value={selectedRange}
//                         onChange={e => setSelectedRange(e.target.value as RangeOption)}
//                         className="border px-2 py-1 rounded"
//                     >
//                         <option>Monthly</option>
//                         <option>Quarterly</option>
//                         <option>Half-Yearly</option>
//                         <option>Yearly</option>
//                         <option>All</option>
//                     </select>

//                     <button
//                         className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
//                         onClick={handleDownloadPDF}
//                     >
//                         <Download size={16} /> Reveneue PDF
//                     </button>
//                     <button
//                         className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
//                         onClick={handleDownloadExcel}
//                     >
//                         <FileSpreadsheet size={16} /> Download Excel
//                     </button>
//                 </div>
//             </div>

//             <ReactApexChart
//                 options={areaChartOptions}
//                 series={filteredSeries}
//                 type="area"
//                 height={350}
//                 width="100%"
//             />
//         </div>
//     );
// };

// export default AreaChart;
//@ts-nocheck
"use client";

import { format } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Download, FileSpreadsheet } from "lucide-react";
import dynamic from "next/dynamic";
import { useState, useMemo } from "react";
import * as XLSX from "xlsx";
import RevenueDescriptionTooltip from "./RevenueDescriptionTooltip";

const ReactApexChart = dynamic(() => import("react-apexcharts"), { ssr: false });

const areaChartOptions = {
    chart: { height: 350, type: "area" },
    dataLabels: { enabled: false },
    stroke: { curve: "smooth", width: 2 },
    legend: { position: "right", verticalAlign: "center" },
    xaxis: { categories: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"] },
    yaxis: { title: { text: "Revenue" } },
    tooltip: { y: { formatter: (val: number) => `$${val}` } },
};

type RangeOption = "Monthly" | "Quarterly" | "Half-Yearly" | "Yearly" | "All";

interface AreaChartProps {
    title: string;
    data: {
        revenue?: { year: string; months: number[] }[];
        description?: string;
    };
}

const AreaChart = ({ title, data }: AreaChartProps) => {
    const [selectedRange, setSelectedRange] = useState<RangeOption>("All");

    const monthsLabels = areaChartOptions.xaxis.categories;

    // ------------------- Filtered Series -----------------
    const filteredSeries = useMemo(() => {
        if (!data?.revenue) return [];

        return data.revenue.map(item => {
            let months = item.months;
            switch (selectedRange) {
                case "Monthly": months = months.slice(-1); break;
                case "Quarterly": months = months.slice(-3); break;
                case "Half-Yearly": months = months.slice(-6); break;
                case "Yearly":
                case "All":
                default: months = months;
            }
            return { name: item.year, data: months };
        });
    }, [data?.revenue, selectedRange]);

    const filteredMonths = useMemo(() => {
        const len = filteredSeries?.[0]?.data?.length || 0;
        return monthsLabels.slice(monthsLabels.length - len);
    }, [filteredSeries]);

    const lastCols = (() => {
        switch (selectedRange) {
            case "Monthly": return 1;
            case "Quarterly": return 3;
            case "Half-Yearly": return 6;
            default: return filteredMonths.length;
        }
    })();

    // ------------------- PDF Download -----------------
    const handleDownloadPDF = async () => {
        if (!filteredSeries.length) return;

        const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
        const pageW = doc.internal.pageSize.getWidth();
        const pageH = doc.internal.pageSize.getHeight();
        const margin = { left: 12, right: 12, top: 16 };
        let currentY = margin.top;

        // Logo
        const logoUrl = "/logo.png";
        const imgProps = await new Promise<HTMLImageElement>((resolve) => {
            const img = new Image();
            img.src = logoUrl;
            img.onload = () => resolve(img);
        });
        const logoWidth = 40;
        const logoHeight = (imgProps.height / imgProps.width) * logoWidth;
        doc.addImage(logoUrl, "PNG", margin.left, currentY, logoWidth, logoHeight);

        // Header
        const centerX = pageW / 2;
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("DgPrint24", centerX, currentY + logoHeight / 2 + 2, { align: "center" });
        currentY += logoHeight + 6;
        doc.setFontSize(14);
        doc.text(title, centerX, currentY, { align: "center" });
        currentY += 6;

        doc.setFontSize(10);
        doc.text(`Generated by Admin at ${format(new Date(), "dd/MM/yyyy hh:mm a")}`, margin.left, currentY);
        currentY += 6;

        // Table
        const tableBody: any[] = [];
        let headerRow: string[] = [];

        if (filteredSeries.length > 1) {
            headerRow = ["Month", ...filteredSeries.map(s => s.name)];
            filteredMonths.forEach((month, idx) => {
                const row = [month];
                filteredSeries.forEach(s => row.push((s.data[idx] ?? 0).toFixed(2)));
                tableBody.push(row);
            });
        } else {
            headerRow = ["Year", "Month", "Revenue"];
            filteredSeries.forEach(s => {
                filteredMonths.forEach((month, idx) => {
                    tableBody.push([s.name, month, (s.data[idx] ?? 0).toFixed(2)]);
                });
            });
        }

        autoTable(doc, {
            startY: currentY + 2,
            head: [headerRow],
            body: tableBody,
            styles: { fontSize: 10, cellPadding: 3 },
            headStyles: { fillColor: [10, 51, 67], textColor: 255 },
            theme: "grid",
            didDrawPage: () => {
                doc.setFontSize(10);
                doc.setTextColor(100);
                doc.text("Developed by ZSI.ai", pageW / 2, pageH - 10, { align: "center" });
            }
        });

        doc.save(`DG-Print24-revenue_report_${selectedRange}_${new Date().toLocaleDateString()}.pdf`);
    };

    // ------------------- Excel Download -----------------
    const handleDownloadExcel = () => {
        if (!filteredSeries.length) return;

        const aoa: any[][] = [];
        aoa.push(["DGPRINT24"]);
        aoa.push([title]);
        aoa.push([`Generated at ${format(new Date(), "MM/dd/yyyy hh:mm a")}`]);
        aoa.push([]);
        aoa.push(["Description"]);
        aoa.push([data?.description || "—"]);
        aoa.push([]);

        let headerRow: string[] = [];
        if (filteredSeries.length > 1) {
            headerRow = ["Month", ...filteredSeries.map(s => s.name)];
            aoa.push(headerRow);
            filteredMonths.forEach((month, idx) => {
                const row = [month];
                filteredSeries.forEach(s => row.push((s.data[idx] ?? 0).toFixed(2)));
                aoa.push(row);
            });
        } else {
            headerRow = ["Year", "Month", "Revenue"];
            aoa.push(headerRow);
            filteredSeries.forEach(s => {
                filteredMonths.forEach((month, idx) => {
                    aoa.push([s.name, month, (s.data[idx] ?? 0).toFixed(2)]);
                });
            });
        }

        const ws = XLSX.utils.aoa_to_sheet(aoa);
        const totalCols = headerRow.length;
        for (let r = 8; r < aoa.length; r++) {
            for (let c = totalCols - lastCols; c < totalCols; c++) {
                const cellRef = XLSX.utils.encode_cell({ r, c });
                if (!ws[cellRef]) continue;
                ws[cellRef].s = { fill: { fgColor: { rgb: "C8E6FF" } } };
            }
        }

        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, "Revenue Report");
        XLSX.writeFile(wb, `DG-Print24-Revenue_Report_${selectedRange}_${new Date().toLocaleDateString()}.xlsx`);
    };

    return (
        <div className="p-10 bg-white shadow-2xl">
            <div className="flex flex-col xl:flex-row md:justify-between gap-4 mb-4 items-start md:items-center">
                <div className="flex items-center gap-2">
                    <h2 className="text-lg font-semibold text-black">{title}</h2>
                    {data?.description && <RevenueDescriptionTooltip description={data.description} />}
                </div>

                <div className="flex gap-2 items-center">
                    <select
                        value={selectedRange}
                        onChange={e => setSelectedRange(e.target.value as RangeOption)}
                        className="border px-2 py-1 rounded"
                    >
                        <option>Monthly</option>
                        <option>Quarterly</option>
                        <option>Half-Yearly</option>
                        <option>Yearly</option>
                        <option>All</option>
                    </select>

                    <button
                        className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
                        onClick={handleDownloadPDF}
                    >
                        <Download size={16} /> Generate PDF
                    </button>
                    <button
                        className="flex items-center gap-2 px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
                        onClick={handleDownloadExcel}
                    >
                        <FileSpreadsheet size={16} /> Download Excel
                    </button>
                </div>
            </div>

            {filteredSeries.length > 0 ? (
                <ReactApexChart
                    options={{ ...areaChartOptions, xaxis: { ...areaChartOptions.xaxis, categories: filteredMonths } }}
                    series={filteredSeries}
                    type="area"
                    height={350}
                    width="100%"
                />
            ) : (
                <p className="text-gray-500 text-center py-20">Loading Revenue Data...</p>
            )}
        </div>
    );
};

export default AreaChart;
