
//@ts-nocheck
"use client";

import { format } from "date-fns";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Download, FileSpreadsheet } from "lucide-react";
import dynamic from "next/dynamic";
import { useEffect, useState } from "react";
import * as XLSX from "xlsx";
import RevenueDescriptionTooltip from "./RevenueDescriptionTooltip";

const ReactApexChart = dynamic(() => import("react-apexcharts"), { ssr: false });

const CategoryBar = (data: { statistics: { category_name: string; total_orders: number[], total_sales: number }[]; description?: string }, isLoading: Boolean) => {

    const [chartData, setChartData] = useState<{ series: any[]; options: any }>({ series: [], options: {} });
    const [description, setDescription] = useState("");
    console.log("category data", data.data)
    useEffect(() => {
        if (!data?.data?.statistics) return;

        const stats = data?.data?.statistics;
        setDescription(data.description || "");

        const categories = stats.map((item: any) => item.category_name);
        const totalOrders = stats.map((item: any) => item.total_orders);
        const totalSales = stats.map((item: any) => item.total_sales);

        setChartData({
            series: [
                { name: "Total Orders", data: totalOrders },
                { name: "Total Sales", data: totalSales },
            ],
            options: {
                chart: { type: "bar", height: 350 },
                colors: ["#2563EB", "#d82d1d"], // blue + red
                plotOptions: { bar: { borderRadius: 4, horizontal: true } },
                dataLabels: { enabled: false },
                xaxis: { categories },
                tooltip: {
                    custom: ({ series, seriesIndex, dataPointIndex, w }: any) => {
                        const category = w.globals.labels[dataPointIndex];
                        const totalOrders = w.config.series.find((s: any) => s.name === "Total Orders")?.data[dataPointIndex] ?? 0;
                        const totalSales = w.config.series.find((s: any) => s.name === "Total Sales")?.data[dataPointIndex] ?? 0;
                        return `
              <div style="padding:10px">
                <strong>${category}</strong>
                <div>🧾 Total Orders: <b>${totalOrders}</b></div>
                <div>💰 Total Sales: <b>$${totalSales.toFixed(2)}</b></div>
              </div>
            `;
                    },
                },
            },
        });
    }, [data]);

    if (isLoading) return <div>Loading chart...</div>;

    // ---------------- PDF Download ----------------
    const handleDownloadPDF = async () => {
        const categories = chartData.options.xaxis.categories;
        const totalOrders = chartData.series.find(s => s.name === "Total Orders")?.data || [];
        const totalSales = chartData.series.find(s => s.name === "Total Sales")?.data || [];
        if (!categories.length) return;

        const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
        const pageW = doc.internal.pageSize.getWidth();
        const margin = { left: 12, right: 12, top: 16, bottom: 12 };
        let currentY = margin.top;

        // Logo
        const logoUrl = "/logo.png"; // must be in /public
        const imgProps = await new Promise<HTMLImageElement>((resolve) => {
            const img = new Image();
            img.src = logoUrl;
            img.onload = () => resolve(img);
        });
        const logoWidth = 40;
        const logoHeight = (imgProps.height / imgProps.width) * logoWidth;
        doc.addImage(logoUrl, "PNG", margin.left, currentY, logoWidth, logoHeight);

        // Header
        const centerX = pageW / 2;
        doc.setFontSize(16);
        doc.setFont("helvetica", "bold");
        doc.text("DgPrint24", centerX, currentY + logoHeight / 2 + 2, { align: "center" });
        currentY += logoHeight + 6;
        doc.setFontSize(14);
        doc.text("Category Report", centerX, currentY, { align: "center" });
        currentY += 6;

        doc.setFontSize(10);
        doc.text(`Generated by Admin at ${format(new Date(), "dd/MM/yyyy hh:mm a")}`, margin.left, currentY);
        currentY += 6;

        // Description box
        if (description) {
            const wrappedDesc = doc.splitTextToSize(description, pageW - margin.left - margin.right - 4);
            const boxHeight = wrappedDesc.length * 6 + 4;
            doc.setDrawColor(10, 51, 67);
            doc.setFillColor(240, 240, 240);
            doc.rect(margin.left, currentY, pageW - margin.left - margin.right, boxHeight, "FD");
            doc.setFontSize(10);
            doc.text(wrappedDesc, margin.left + 2, currentY + 6);
            currentY += boxHeight + 4;
        }

        // Table
        const tableBody = categories.map((cat: string, idx: number) => [
            cat,
            totalOrders[idx] ?? 0,
            `$${totalSales[idx]?.toFixed(2) ?? 0}`
        ]);
        const totalOrdersSum = totalOrders.reduce((sum: number, n: number) => sum + n, 0);
        const totalSalesSum = totalSales.reduce((sum: number, n: number) => sum + n, 0);
        tableBody.push(["Total", totalOrdersSum, `$${totalSalesSum.toFixed(2)}`]);

        autoTable(doc, {
            startY: currentY + 2,
            head: [["Category", "Total Orders", "Total Sales"]],
            body: tableBody,
            styles: { fontSize: 10, cellPadding: 3 },
            headStyles: { fillColor: [10, 51, 67], textColor: 255 },
            footStyles: { fillColor: [50, 50, 50], textColor: 255, fontStyle: "bold" },
            theme: "grid",
            didDrawPage: (data) => {
                const pageH = doc.internal.pageSize.getHeight(); // ✅ get page height
                doc.setFontSize(10);
                doc.setTextColor(100);
                doc.text("Developed by ZSI.ai", pageW / 2, pageH - 10, { align: "center" });
            }

        });

        doc.save(`DG-Print24-category_report_${new Date().toLocaleDateString()}.pdf`);
    };

    // ---------------- Excel Download ----------------
    const handleDownloadExcel = () => {
        const categories = chartData.options.xaxis.categories;
        const totalOrders = chartData.series.find(s => s.name === "Total Orders")?.data || [];
        const totalSales = chartData.series.find(s => s.name === "Total Sales")?.data || [];
        if (!categories.length) return;

        const aoa: any[][] = [];
        aoa.push(["DGPRINT24"]);
        aoa.push(["Category Report"]);
        aoa.push([`Generated by Admin at ${format(new Date(), "dd/MM/yyyy hh:mm a")}`]);
        aoa.push([]);
        aoa.push(["Description"]);
        aoa.push([description || "—"]);
        aoa.push([]);
        aoa.push(["Category", "Total Orders", "Total Sales"]);

        categories.forEach((cat: string, idx: number) => {
            aoa.push([cat, totalOrders[idx] ?? 0, totalSales[idx]?.toFixed(2) ?? 0]);
        });

        // totals
        const totalOrdersSum = totalOrders.reduce((sum: number, n: number) => sum + n, 0);
        const totalSalesSum = totalSales.reduce((sum: number, n: number) => sum + n, 0);
        aoa.push(["Total", totalOrdersSum, totalSalesSum.toFixed(2)]);

        const ws = XLSX.utils.aoa_to_sheet(aoa);
        const wb = XLSX.utils.book_new();
        XLSX.utils.book_append_sheet(wb, ws, "Category Report");
        XLSX.writeFile(wb, `category_report_${new Date().toLocaleDateString()}.xlsx`);
    };

    return (
        <div className="p-10 border-2 shadow-2xl overflow-hidden bg-white w-full">
            <div className="flex flex-col xl:flex-row justify-between  items-center gap-2 mb-4">
                <div className="flex gap-1"> <h2 className="text-lg font-semibold text-black">
                    Total Sales and Orders Across Product Categories
                </h2>
                    {description && <RevenueDescriptionTooltip description={description} />}</div>


                <div className="flex gap-2">
                    <button
                        className="flex items-center cursor-pointer gap-2 px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700"
                        onClick={handleDownloadPDF}
                    >
                        <Download size={16} /> Download PDF
                    </button>
                    <button
                        className="flex items-center cursor-pointer gap-2 px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
                        onClick={handleDownloadExcel}
                    >
                        <FileSpreadsheet size={16} /> Download Excel
                    </button>
                </div>

            </div>
            <div id="chart" className="mb-4">
                <ReactApexChart options={chartData.options} series={chartData.series} type="bar" height={350} />
            </div>

        </div>
    );
};

export default CategoryBar;
